defaults:
  - _self_

# Data paths
base_data_path: /data1/jy384/research/Data/UnimodalSROB/ns/
output_path: ${base_data_path}

# Output file name
output_file: "combined_dataset.npy"

# List of mu values to process
mu_values:
  - 0.002000
  - 0.001333
  #  -----
  - 0.001111 # RE 90
  #  -----
  - 0.001000 # RE 100
  # -----
  - 0.000909 # RE 110
  # -----
  - 0.000800 # RE 125
  - 0.000667
  - 0.000571
  - 0.000500

  # - 0.001667
  # - 0.001111
  # - 0.000909
  # - 0.000714
  # - 0.000625
  # - 0.000526

# Common parameters
L_c: 0.1 # Characteristic length (cylinder diameter)
U_c: 1.0 # Characteristic velocity (average inlet velocity)
rho: 1
