defaults:
  - _self_

# List of mu values to process
mu_values:
  - 0.002000
  - 0.001333
  - 0.001000
  - 0.000800
  - 0.000667
  - 0.000571
  - 0.000500

  - 0.001667
  - 0.001111
  - 0.000909
  - 0.000714
  - 0.000625
  - 0.000526

# Data extraction settings
base_data_path: /data1/jy384/research/Data/UnimodalSROB/ns/ # Path to the folder containing all Re_*_mu_* folders
output_base_path: ${base_data_path} # Base path for output files, can be overridden
bp_filename_prefix: "dfg2D-3-u"
variable: "u"

# Re-use some settings from the simulation config
t: 0
T: 8
dt: 0.000625
num_steps: null

# Fluid properties
rho: 1

# Geometry parameters
L: 2.2
H: 0.41
c_x: 0.2
c_y: 0.2
r: 0.05

# Reynolds number calculation
L_c: 0.1 # Characteristic length (cylinder diameter)
U_c: 1.0 # Characteristic velocity (average inlet velocity)
Re: null
